-- ["Gelendzhik"] = "Gelendzhik",
-- ["Krasnodar_Pashkovsky"] = "Krasnodar-Pashkovsky",
-- ["Sukhumi_Babushara"] = "Sukhumi-Babushara",
-- ["Gudauta"] = "Gudauta",
-- ["Batumi"] = "Batumi",
-- ["Senaki_Kolkhi"] = "Senaki-Kolkhi",
-- ["Kobuleti"] = "Kobuleti",
-- ["Kutaisi"] = "Kutaisi",
-- ["Tbilisi_Lochini"] = "Tbilisi-Lochini",
-- ["Soganlug"] = "Soganlug",
-- ["Vaziani"] = "Vaziani",
-- ["Anapa_Vityazevo"] = "Anapa-Vityazevo",
-- ["Krasnodar_Center"] = "Krasnodar-Center",
-- ["Novorossiysk"] = "Novorossiysk",
-- ["Krymsk"] = "Krymsk",
-- ["Maykop_Khanskaya"] = "Maykop-Khanskaya",
-- ["Sochi_Adler"] = "Sochi-Adler",
-- ["Mineralnye_Vody"] = "Mineralnye Vody",
-- ["Nalchik"] = "Nalchik",
-- ["Mozdok"] = "Mozdok",
-- ["Beslan"] = "Beslan",

A2AConfig = 
{
    {
        groupPrefix = "capMig29",
        spawnedGroupPrefix = "CapMig29S",
        minAltitude = 5500,
        maxAltitude = 10000,
        airBase = "Gudauta",
        isCap = true,
        isGci = false,
        grouping = 2,
        overhead = 1,
        airCraftLimit = 8,
        minFrontlineDistance = 40000,
        maxFrontlineDistance = 100000
    },
    {
        groupPrefix = "gciSu27",
        spawnedGroupPrefix = "gciMig29S",
        minAltitude = 2000,
        maxAltitude = 11000,
        airBase = "Gudauta",
        isCap = false,
        isGci = true,
        grouping = 2,
        overhead = 1,
        airCraftLimit = 8,
        minFrontlineDistance = 40000,
        maxFrontlineDistance = 100000
    }
    -- {
    --     groupPrefix = "BlueGeorgianCAPF16",
    --     spawnedGroupPrefix = "GeorgianCAPF16",
    --     minAltitude = 3000,
    --     maxAltitude = 6000,
    --     airBase = "Soganlug",
    --     isCap = true,
    --     isGci = false,
    --     grouping = 2,
    --     overhead = 1,
    --     airCraftLimit = 8,
    --     minFrontlineDistance = 40000,
    --     maxFrontlineDistance = 100000
    -- }
}